(deftheme sanityinc-solarized-dark-chen
  "Created 2017-10-12.")

(custom-theme-set-variables
 'sanityinc-solarized-dark-chen
 '(ansi-color-names-vector ["#839496" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#eee8d5"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'sanityinc-solarized-dark-chen
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#586e75" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-doc-face ((t (:foreground "#ffffff"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#dc322f"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#dc322f")))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:style wave :color "#2aa198")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#b58900")))))
 '(flycheck-fringe-error ((t (:background "#dc322f" :foreground "#2fdc32"))))
 '(flycheck-fringe-info ((t (:background "#2aa198" :foreground "#ffffff"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#cb4b16"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#073642"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#002b36" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#002b36" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#2aa198" :background "#002b36" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#002b36" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#dc322f" :background "#002b36"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#2aa198" :weight normal :underline nil))))
 '(cursor ((((class color) (min-colors 89)) (:background "#93a1a1"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#073642" :foreground "#839496"))))
 '(linum ((((class color) (min-colors 89)) (:background "#073642" :foreground "#859900" :italic nil))))
 '(border ((((class color) (min-colors 89)) (:background "#073642"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#073642"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground nil :background "#073642" :weight normal :box (:line-width 1 :color "#839496")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:background nil :foreground "#ffffff"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#586e75" :background "#073642" :weight normal :box (:line-width 1 :color "#839496")))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#93a1a1"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#d33682" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(region ((((class color) (min-colors 89)) (:foreground "#93a1a1" :inverse-video t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#073642"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#d33682" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#dc322f" :underline nil))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background nil :foreground nil :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#d33682" :foreground "#002b36"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#6c71c4"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#cb4b16"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#2aa198" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "#268bd2" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#d33682"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "#859900" :background "#859900"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#268bd2"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "#b58900" :background "#b58900"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(macrostep-expansion-highlight-face ((((class color) (min-colors 89)) (:inherit highlight :foreground nil))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#839496"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#859900" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#586e75"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#073642" :box (:line-width 1 :color "#839496")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#b58900"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#859900"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#dc322f"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(company-preview ((((class color) (min-colors 89)) (:foreground "#657b83" :background "#eee8d5"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#b58900"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit company-preview :foreground "#268bd2"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#eee8d5"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#073642"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#b58900"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:inherit company-tooltip-selection :foreground "#b58900"))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#268bd2"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:inherit company-tooltip :foreground "#859900"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:inherit (quote company-tooltip) :background "#073642"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#eee8d5"))))
 '(company-echo-common ((((class color) (min-colors 89)) (:inherit company-echo :foreground "#b58900"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#839496" :background "#002b36")))))

(provide-theme 'sanityinc-solarized-dark-chen)
